#!/bin/bash
clear
echo -e "\a\a\e[36;1m
#######                                                   #     #
   #    ###### #####  #    # #    # #    #       #    #  ##    ##
   #    #      #    # ##  ## #    #  #  #         #  #  # #   # #
   #    #####  #    # # ## # #    #   ##   #####   ##     #     #
   #    #      #####  #    # #    #   ##           ##     #     #
   #    #      #   #  #    # #    #  #  #         #  #    #     #
   #    ###### #    # #    #  ####  #    #       #    # ##### #####
                                                     \e[0m XFCE4-Desktop

\e[33;1m---Installing Termux-x11 Xfce4 Desktop\e[0m"
echo ---updating system...
apt update && apt upgrade -y
echo ---installing requirements.....
apt install toilet figlet x11-repo -y
echo ---installing Xfce4-Desktop...
apt install xfce4 xfce4-terminal xwayland dbus termux-x11-nightly firefox neovim -y
rm -rf $PREFIX/etc/motd
cat > x <<- EOF
toilet -f slant Termux-X11
echo -e "Welcom to \e[32mTermux-X11\e[0m by Alienkrishn"
echo -e "
Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Adding your name on banner:
 *customizing x11 : change-banner
"
EOF
bash x > $PREFIX/etc/motd
rm x
curl -LO https://raw.githubusercontent.com/Anon4You/Termux-x11-xfce4/main/lib/bash.bashrc
mv bash.bashrc $PREFIX/etc
echo "alienx" > $PATH/change-banner
chmod +x $PATH/change-banner
curl -LO https://raw.githubusercontent.com/Anon4You/Termux-x11-xfce4/main/lib/alienx
mv alienx $PATH && chmod +x $PATH/alienx
echo installed successfully exiting termux open it again...
sleep 3
kill -9 $PPID

