#!/bin/bash
clear
echo -e "\a\a\e[36;1m
#######                                                   #     #
   #    ###### #####  #    # #    # #    #       #    #  ##    ##
   #    #      #    # ##  ## #    #  #  #         #  #  # #   # #
   #    #####  #    # # ## # #    #   ##   #####   ##     #     #
   #    #      #####  #    # #    #   ##           ##     #     #
   #    #      #   #  #    # #    #  #  #         #  #    #     #
   #    ###### #    # #    #  ####  #    #       #    # ##### #####
                                                     \e[0m XFCE4-Desktop

\e[33;1m---Installing Termux-x11 Xfce4 Desktop\e[0m"
echo ---updating system...
apt update && apt upgrade -y
echo ---installing requirements.....
apt install toilet figlet x11-repo -y
echo ---installing Xfce4-Desktop...
apt install xfce4 xfce4-terminal xwayland dbus termux-x11-nightly xfce4-goodies firefox neovim -y
rm -rf $PREFIX/etc/motd
cat > x <<- EOF
toilet -f slant Termux-X11
echo -e "Welcom to \e[32mTermux-X11\e[0m by Alienkrishn"
echo -e "
Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Starting Termux-x11 Desktop
* to start x11-xfce4 : xstart
"
EOF
bash x > $PREFIX/etc/motd
rm x
curl -LO https://raw.githubusercontent.com/Anon4You/kalilinux/main/xstart
mv xstart $PATH && chmod +x $PATH/xstart
curl -LO https://raw.githubusercontent.com/Anon4You/Termux-x11-xfce4/main/lib/font.ttf
mv font.ttf .termux
curl -LO https://raw.githubusercontent.com/Anon4You/Termux-x11-xfce4/main/lib/colors.properties
mv colors.properties .termux
curl -LO https://raw.githubusercontent.com/Anon4You/Termux-x11-xfce4/main/lib/bash.bashrc
mv bash.bashrc $PREFIX/etc
echo installed successfully exiting termux open it again...

